### ISSUE TITLE
Switching controllers during runtime while using MoveIt

### ISSUE THREAD

**Issue by Cody-Vu** [moveit/moveit#3702]
I work with the franka panda robot using moveit and have a question about switching controllers. Is it possible to configure multiple controllers in the moveit_controllers.yaml file, for example position and effort controller:
controller_list:
 ```
 - name: effort_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
  - name: position_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - panda_joint1
      - panda_joint2
      - panda_joint3
      - panda_joint4
      - panda_joint5
      - panda_joint6
      - panda_joint7
```
and switch them during runtime while the moveit node is constantly running? Right now I have the issue that moveit is only sending the trajectory to the default controller, even if I stop the default controller and run the other one instead. In the franka control node I get the error:

Can't accept new action goals. Controller is not running.

Is there a way to switch the controllers during runtime while using moveit ? 
Thanks in advance!

**Comment by LeroyR** [comment]
You need to use a different `moveit_controller_manager` plugin that supports switching the running controllers

e.g. [`moveit_ros_control_interface::MoveItControllerManager`](https://github.com/moveit/moveit/blob/master/moveit_plugins/moveit_ros_control_interface/README.md)

Most robots default to `moveit_simple_controller_manager/MoveItSimpleControllerManager` which is not able to switch controllers.

**Comment by Cody-Vu** [comment]
Hey @LeroyR , I tried using the MoveItControllerManager, but had the problem, that MoveIt itself is stopping and loading controllers without my permission. MoveIt then chooses itself which controller to use. But my goal is to use the controller which is currently active. so I can manually decide which controller will be used. Do you know how I can achieve this behaviour?

**Comment by rhaschke** [comment]
The ROS parameters `moveit_manage_controllers` controls whether MoveIt is allowed to switch to its preferred controllers or not. It is true by default:
https://github.com/moveit/moveit/blob/fcbdce7014202075081da98bf10b8df61219ee4b/moveit_setup_assistant/templates/moveit_config_pkg_template/launch/move_group.launch#L73
as well as in panda_moveit_config:
https://github.com/moveit/panda_moveit_config/blob/a86da56ab1c756a851d8ee2a06dd04266d1653d6/launch/move_group.launch#L85

**Comment by Cody-Vu** [comment]
Hello @rhaschke , thanks for the info. I set the `moveit_manage_controllers` as false. But after I switched the default controller I receive this error:

[ INFO] [1746010034.191611948, 113.767000000]: Combined planning and execution request received for MoveGroup action. Forwarding to planning and execution pipeline.
[ INFO] [1746010034.191667338, 113.767000000]: Planning attempt 1 of at most 1
[ INFO] [1746010034.191962335, 113.767000000]: Using planning pipeline 'ompl'
[ INFO] [1746010034.193872621, 113.769000000]: Planner configuration 'panda_arm' will use planner 'geometric::RRTConnect'. Additional configuration parameters will be set when the planner is constructed.
[ INFO] [1746010034.194620486, 113.770000000]: panda_arm/panda_arm: Starting planning with 1 states already in datastructure
[ INFO] [1746010034.194694637, 113.770000000]: panda_arm/panda_arm: Starting planning with 1 states already in datastructure
[ INFO] [1746010034.194902667, 113.770000000]: panda_arm/panda_arm: Starting planning with 1 states already in datastructure
[ INFO] [1746010034.194960496, 113.771000000]: panda_arm/panda_arm: Starting planning with 1 states already in datastructure
[ INFO] [1746010034.206840222, 113.782000000]: panda_arm/panda_arm: Created 4 states (2 start + 2 goal)
[ INFO] [1746010034.207002307, 113.782000000]: panda_arm/panda_arm: Created 4 states (2 start + 2 goal)
[ INFO] [1746010034.208179887, 113.783000000]: panda_arm/panda_arm: Created 4 states (2 start + 2 goal)
[ INFO] [1746010034.208446383, 113.784000000]: panda_arm/panda_arm: Created 5 states (2 start + 3 goal)
[ INFO] [1746010034.208531471, 113.784000000]: ParallelPlan::solve(): Solution found by one or more threads in 0.014051 seconds
[ INFO] [1746010034.212875574, 113.788000000]: SimpleSetup: Path simplification took 0.004239 seconds and changed from 3 to 2 states
[ INFO] [1746010034.227615150, 113.800000000]: Completed trajectory execution with status ABORTED ...
[ INFO] [1746010034.243634723, 113.816000000]: ABORTED: CONTROL_FAILED

I tried switching between position and effort controller. For the default controller it successfully executes the trajectory. If I switch to the other one, it calculates the trajectory as usual but cannot execute it. Anything else I have to adjust?

**Comment by rhaschke** [comment]
Could you please post the console log of your ros_control node? You just posted the output of the move_group node.
The question behind this is: Does MoveIt abort the trajectory execution or is it the ros_control node?

**Comment by rhaschke** [comment]
No need to go to real hardware. Gazebo is running the ros_control node in your case. Are you using the standard `panda_moveit_config` package or did you do any relevant modifications?

**Comment by Cody-Vu** [comment]
For now I use the standard `panda_moveit_config` package. I added the controller list to a moveit_controllers.yaml like shown in my first comment. And in the `gazebo_controllers.yaml` I am loading the parameters for the controllers.

**Comment by rhaschke** [comment]
As far as I understand, your original issue was solved using the ROS parameter `/move_group/moveit_manage_controllers=false`. If so, please close this issue.

The remaining issue with the Cartesian impedance controller points to a misconfiguration. There are no known controllers listed!

**Comment by Cody-Vu** [comment]
While the ROS parameter `/move_group/moveit_manage_controllers=false` helped address part of the original issue, I’m still encountering problems when switching controllers. Specifically, after using one controller and attempting to switch to another, the execution aborts and fails.

**Comment by rhaschke** [comment]
Please provide more details to allow to reproduce the problem: 
1. Provide the panda_moveit_config package with all your modifications. 
2. Exactly describe what you are doing, i.e. from which to which controllers do you switch? When do you execute?
3. Provide console logs.

**Comment by Cody-Vu** [comment]
1. I added the list of controllers to [ros_controllers..yaml](https://github.com/Cody-Vu/panda_moveit_config/blob/noetic-devel/config/ros_controllers.yaml).
2. I added the controller parameters to [gazebo_controllers.yaml](https://github.com/Cody-Vu/panda_moveit_config/blob/noetic-devel/config/gazebo_controllers.yaml#L6)
3. I am loading the controller list to the parameter server by adding this [line](https://github.com/Cody-Vu/panda_moveit_config/blob/noetic-devel/launch/ros_control_moveit_controller_manager.launch.xml#L6) to `ros_control_moveit_controller_manager.launch.xml`
4. I load the controller configuration to [demo_gazebo.launch](https://github.com/Cody-Vu/panda_moveit_config/blob/noetic-devel/launch/demo_gazebo.launch#L15) and changed from `simple` to `ros_control` [here](https://github.com/Cody-Vu/panda_moveit_config/blob/noetic-devel/launch/demo_gazebo.launch#L28) and [here](https://github.com/Cody-Vu/panda_moveit_config/blob/noetic-devel/launch/move_group.launch#L17)
5. I set the moveit_manage_controllers to false [here](https://github.com/Cody-Vu/panda_moveit_config/blob/noetic-devel/launch/move_group.launch#L85) and [here](https://github.com/Cody-Vu/panda_moveit_config/blob/noetic-devel/launch/trajectory_execution.launch.xml#L9)

I start with one controller for example `the position_joint_trajectory_controller` and execute a motion. Then I stop this controller, load the `effort_joint_trajectory_controller` and start it. Then I try to execute a motion with this controller and receive this info:

Completed trajectory execution with status ABORTED ...
[ INFO] [1746176987.208709857, 26.886000000]: ABORTED: CONTROL_FAILED

I get the same result the other way around.

**Comment by rhaschke** [comment]
Thanks. Using your fork, I was able to reproduce the issue. Cleaning up your changes (https://github.com/Cody-Vu/panda_moveit_config/pull/1), however, resolved the issue for me:
```
...
INFO 10:50:37, 00:00:54 ros.moveit_planners_ompl.ompl: ParallelPlan::solve(): Solution found by one or more threads in 0.012780 seconds
INFO 10:50:37, 00:00:54 ros.moveit_planners_ompl.ompl: SimpleSetup: Path simplification took 0.007304 seconds and changed from 4 to 2 states
INFO 10:50:42, 00:00:59 ros.moveit_simple_controller_manager.SimpleControllerManager: Controller '/position_joint_trajectory_controller' successfully finished
INFO 10:50:42, 00:00:59 ros.moveit_ros_planning.trajectory_execution_manager: Completed trajectory execution with status SUCCEEDED ...
...
INFO 10:50:55, 00:01:11 ros.moveit_planners_ompl.ompl: ParallelPlan::solve(): Solution found by one or more threads in 0.012103 seconds
INFO 10:50:55, 00:01:11 ros.moveit_planners_ompl.ompl: SimpleSetup: Path simplification took 0.006507 seconds and changed from 3 to 2 states
INFO 10:51:00, 00:01:16 ros.moveit_simple_controller_manager.SimpleControllerManager: Controller '/effort_joint_trajectory_controller' successfully finished
INFO 10:51:00, 00:01:16 ros.moveit_ros_planning.trajectory_execution_manager: Completed trajectory execution with status SUCCEEDED ...
...
INFO 10:51:29, 00:01:45 ros.moveit_planners_ompl.ompl: ParallelPlan::solve(): Solution found by one or more threads in 0.012574 seconds
INFO 10:51:29, 00:01:45 ros.moveit_planners_ompl.ompl: SimpleSetup: Path simplification took 0.005749 seconds and changed from 3 to 2 states
INFO 10:51:34, 00:01:51 ros.moveit_simple_controller_manager.SimpleControllerManager: Controller '/position_joint_trajectory_controller' successfully finished
INFO 10:51:34, 00:01:51 ros.moveit_ros_planning.trajectory_execution_manager: Completed trajectory execution with status SUCCEEDED ...
```

**Comment by Cody-Vu** [comment]
I accepted your pull request and used the `panda_moveit_config `the exact same as you yposted, but somehow I get the same issue as before (ABORTED: CONTROL_FAILED). 

> INFO 10:50:42, 00:00:59 ros.moveit_simple_controller_manager.SimpleControllerManager: Controller '/position_joint_trajectory_controller' successfully finished

Are you using the `SimpleControllerManager`?

**Comment by rhaschke** [comment]
> I get the same issue as before (ABORTED: CONTROL_FAILED).

Are you sure, you correctly launched from scratch? Do you had another `roscore` running maybe?

> Are you using the `SimpleControllerManager`?

No. I was confused by the logger name as well. However, the ros_control MoveItControllerManager reuses `FollowJointTrajectoryControllerHandle` of `MoveItSimpleControllerManager`:
https://github.com/moveit/moveit/blob/fcbdce7014202075081da98bf10b8df61219ee4b/moveit_plugins/moveit_ros_control_interface/src/joint_trajectory_controller_plugin.cpp
